#Make sure that you're in mercari-build-training-2022/ directory

FROM python:3.10.4-slim-buster

# STEP4-4では以下は変更しない

COPY db/ ./db

WORKDIR /app

COPY python/ .

RUN pip3 install -r requirements.txt


CMD [ "uvicorn", "main:app", "--reload", "--host", "0.0.0.0", "--port", "9000"]
